<a href="https://colab.research.google.com/github/Subhranshu-123/BIKE2/blob/main/WORLD_ECONOMIC_DATA(HUMAN_DEVELOPMENT_INDEX).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

DATA MANIPULATION

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('/content/HDI.csv')

In [ ]:
df.head(5)

,iso3,country,hdicode,region,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,NaN,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [ ]:
df.tail(5)

,iso3,country,hdicode,region,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
201,ZZG.ECA,Europe and Central Asia,NaN,NaN,NaN,0.664,0.661,0.654,0.652,0.647,...,13.107171,14.172082,14.189127,14.523162,13.791770,13.618078,13.914030,14.087293,14.091826,14.096719
202,ZZH.LAC,Latin America and the Caribbean,NaN,NaN,NaN,0.633,0.638,0.643,0.648,0.654,...,14.114108,14.493145,14.080904,14.146026,13.325144,13.604555,13.151315,13.296195,13.290914,13.284745
203,ZZI.SA,South Asia,NaN,NaN,NaN,0.442,0.447,0.453,0.457,0.462,...,4.699407,4.584935,4.486500,4.610546,4.624886,4.740263,5.000024,5.110230,5.106447,5.102134
204,ZZJ.SSA,Sub-Saharan Africa,NaN,NaN,NaN,0.407,0.410,0.410,0.411,0.413,...,3.437760,3.530479,3.491150,3.494860,3.415511,3.256156,3.145930,3.151076,3.146092,3.140740
205,ZZK.WORLD,World,NaN,NaN,NaN,0.601,0.604,0.607,0.610,0.614,...,12.186601,12.474065,12.520563,12.372667,12.277707,12.277878,12.220286,12.375236,12.325166,12.271920

In [ ]:
df.shape

(206, 1008)

In [ ]:
df.columns

Index(['iso3', 'country', 'hdicode', 'region', 'hdi_rank_2021', 'hdi_1990',
       'hdi_1991', 'hdi_1992', 'hdi_1993', 'hdi_1994',
       ...
       'mf_2012', 'mf_2013', 'mf_2014', 'mf_2015', 'mf_2016', 'mf_2017',
       'mf_2018', 'mf_2019', 'mf_2020', 'mf_2021'],
      dtype='object', length=1008)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206 entries, 0 to 205
Columns: 1008 entries, iso3 to mf_2021
dtypes: float64(1004), object(4)
memory usage: 1.6+ MB

In [ ]:
df.describe()

,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,hdi_1995,hdi_1996,hdi_1997,hdi_1998,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
count,191.000000,152.000000,152.000000,152.000000,152.000000,152.000000,163.000000,163.000000,163.000000,163.000000,...,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000,168.000000
mean,95.811518,0.595112,0.597862,0.600493,0.604474,0.609329,0.613908,0.619663,0.624975,0.630417,...,15.249784,15.385926,15.347629,15.352632,15.342119,15.491780,14.597416,14.776332,14.775408,14.774396
std,55.307333,0.161918,0.161921,0.162193,0.163122,0.163818,0.162789,0.163461,0.164299,0.165177,...,14.134572,14.555342,14.363092,14.680340,15.015809,15.333709,13.581871,14.266308,14.266504,14.266706
min,1.000000,0.216000,0.218000,0.222000,0.227000,0.232000,0.238000,0.243000,0.248000,0.256000,...,0.430000,0.420000,0.450000,0.560000,0.600000,0.610000,0.500000,0.470000,0.470000,0.470000
25%,48.500000,0.477750,0.477000,0.475250,0.474250,0.476500,0.480500,0.488500,0.490000,0.492000,...,4.597500,4.525000,4.452375,4.457500,4.517500,4.575000,4.612500,4.732500,4.732500,4.732500
50%,96.000000,0.621500,0.623500,0.622000,0.624000,0.623500,0.642000,0.650000,0.651000,0.657000,...,10.907725,11.272314,10.745000,10.260000,10.590000,10.895000,11.215000,11.030000,11.030000,11.030000
75%,143.500000,0.725500,0.727000,0.723750,0.724250,0.733750,0.737000,0.743000,0.752500,0.759000,...,20.345000,20.397500,20.227500,20.187500,19.350000,19.757500,18.432500,17.932500,17.932500,17.932500
max,191.000000,0.872000,0.873000,0.878000,0.880000,0.884000,0.885000,0.887000,0.890000,0.895000,...,74.560000,82.970000,81.100000,86.780000,83.510000,88.700000,71.160000,85.700000,85.700000,85.700000

In [ ]:
df.isnull().sum()

iso3              0
country           0
hdicode          15
region           55
hdi_rank_2021    15
                 ..
mf_2017          38
mf_2018          38
mf_2019          38
mf_2020          38
mf_2021          38
Length: 1008, dtype: int64

In [ ]:
print(df.columns.tolist())

['iso3', 'country', 'hdicode', 'region', 'hdi_rank_2021', 'hdi_1990', 'hdi_1991', 'hdi_1992', 'hdi_1993', 'hdi_1994', 'hdi_1995', 'hdi_1996', 'hdi_1997', 'hdi_1998', 'hdi_1999', 'hdi_2000', 'hdi_2001', 'hdi_2002', 'hdi_2003', 'hdi_2004', 'hdi_2005', 'hdi_2006', 'hdi_2007', 'hdi_2008', 'hdi_2009', 'hdi_2010', 'hdi_2011', 'hdi_2012', 'hdi_2013', 'hdi_2014', 'hdi_2015', 'hdi_2016', 'hdi_2017', 'hdi_2018', 'hdi_2019', 'hdi_2020', 'hdi_2021', 'le_1990', 'le_1991', 'le_1992', 'le_1993', 'le_1994', 'le_1995', 'le_1996', 'le_1997', 'le_1998', 'le_1999', 'le_2000', 'le_2001', 'le_2002', 'le_2003', 'le_2004', 'le_2005', 'le_2006', 'le_2007', 'le_2008', 'le_2009', 'le_2010', 'le_2011', 'le_2012', 'le_2013', 'le_2014', 'le_2015', 'le_2016', 'le_2017', 'le_2018', 'le_2019', 'le_2020', 'le_2021', 'eys_1990', 'eys_1991', 'eys_1992', 'eys_1993', 'eys_1994', 'eys_1995', 'eys_1996', 'eys_1997', 'eys_1998', 'eys_1999', 'eys_2000', 'eys_2001', 'eys_2002', 'eys_2003', 'eys_2004', 'eys_2005', 'eys_2006', 'eys_2007', 'eys_2008', 'eys_2009', 'eys_2010', 'eys_2011', 'eys_2012', 'eys_2013', 'eys_2014', 'eys_2015', 'eys_2016', 'eys_2017', 'eys_2018', 'eys_2019', 'eys_2020', 'eys_2021', 'mys_1990', 'mys_1991', 'mys_1992', 'mys_1993', 'mys_1994', 'mys_1995', 'mys_1996', 'mys_1997', 'mys_1998', 'mys_1999', 'mys_2000', 'mys_2001', 'mys_2002', 'mys_2003', 'mys_2004', 'mys_2005', 'mys_2006', 'mys_2007', 'mys_2008', 'mys_2009', 'mys_2010', 'mys_2011', 'mys_2012', 'mys_2013', 'mys_2014', 'mys_2015', 'mys_2016', 'mys_2017', 'mys_2018', 'mys_2019', 'mys_2020', 'mys_2021', 'gnipc_1990', 'gnipc_1991', 'gnipc_1992', 'gnipc_1993', 'gnipc_1994', 'gnipc_1995', 'gnipc_1996', 'gnipc_1997', 'gnipc_1998', 'gnipc_1999', 'gnipc_2000', 'gnipc_2001', 'gnipc_2002', 'gnipc_2003', 'gnipc_2004', 'gnipc_2005', 'gnipc_2006', 'gnipc_2007', 'gnipc_2008', 'gnipc_2009', 'gnipc_2010', 'gnipc_2011', 'gnipc_2012', 'gnipc_2013', 'gnipc_2014', 'gnipc_2015', 'gnipc_2016', 'gnipc_2017', 'gnipc_2018', 'gnipc_2019', 'gnipc_2020', 'gnipc_2021', 'gdi_group_2021', 'gdi_1990', 'gdi_1991', 'gdi_1992', 'gdi_1993', 'gdi_1994', 'gdi_1995', 'gdi_1996', 'gdi_1997', 'gdi_1998', 'gdi_1999', 'gdi_2000', 'gdi_2001', 'gdi_2002', 'gdi_2003', 'gdi_2004', 'gdi_2005', 'gdi_2006', 'gdi_2007', 'gdi_2008', 'gdi_2009', 'gdi_2010', 'gdi_2011', 'gdi_2012', 'gdi_2013', 'gdi_2014', 'gdi_2015', 'gdi_2016', 'gdi_2017', 'gdi_2018', 'gdi_2019', 'gdi_2020', 'gdi_2021', 'hdi_f_1990', 'hdi_f_1991', 'hdi_f_1992', 'hdi_f_1993', 'hdi_f_1994', 'hdi_f_1995', 'hdi_f_1996', 'hdi_f_1997', 'hdi_f_1998', 'hdi_f_1999', 'hdi_f_2000', 'hdi_f_2001', 'hdi_f_2002', 'hdi_f_2003', 'hdi_f_2004', 'hdi_f_2005', 'hdi_f_2006', 'hdi_f_2007', 'hdi_f_2008', 'hdi_f_2009', 'hdi_f_2010', 'hdi_f_2011', 'hdi_f_2012', 'hdi_f_2013', 'hdi_f_2014', 'hdi_f_2015', 'hdi_f_2016', 'hdi_f_2017', 'hdi_f_2018', 'hdi_f_2019', 'hdi_f_2020', 'hdi_f_2021', 'le_f_1990', 'le_f_1991', 'le_f_1992', 'le_f_1993', 'le_f_1994', 'le_f_1995', 'le_f_1996', 'le_f_1997', 'le_f_1998', 'le_f_1999', 'le_f_2000', 'le_f_2001', 'le_f_2002', 'le_f_2003', 'le_f_2004', 'le_f_2005', 'le_f_2006', 'le_f_2007', 'le_f_2008', 'le_f_2009', 'le_f_2010', 'le_f_2011', 'le_f_2012', 'le_f_2013', 'le_f_2014', 'le_f_2015', 'le_f_2016', 'le_f_2017', 'le_f_2018', 'le_f_2019', 'le_f_2020', 'le_f_2021', 'eys_f_1990', 'eys_f_1991', 'eys_f_1992', 'eys_f_1993', 'eys_f_1994', 'eys_f_1995', 'eys_f_1996', 'eys_f_1997', 'eys_f_1998', 'eys_f_1999', 'eys_f_2000', 'eys_f_2001', 'eys_f_2002', 'eys_f_2003', 'eys_f_2004', 'eys_f_2005', 'eys_f_2006', 'eys_f_2007', 'eys_f_2008', 'eys_f_2009', 'eys_f_2010', 'eys_f_2011', 'eys_f_2012', 'eys_f_2013', 'eys_f_2014', 'eys_f_2015', 'eys_f_2016', 'eys_f_2017', 'eys_f_2018', 'eys_f_2019', 'eys_f_2020', 'eys_f_2021', 'mys_f_1990', 'mys_f_1991', 'mys_f_1992', 'mys_f_1993', 'mys_f_1994', 'mys_f_1995', 'mys_f_1996', 'mys_f_1997', 'mys_f_1998', 'mys_f_1999', 'mys_f_2000', 'mys_f_2001', 'mys_f_2002', 'mys_f_2003', 'mys_f_2004', 'mys_f_2005', 'mys_f_2006', 'mys_f_2007', 'mys_f_2008', 'mys_f_2009', 'mys_f_2010', 'mys_f_2011', 'mys_f_2012', 'mys_f_2013', 'mys_f_2014', 'mys_f_2015', 'mys_f_2016', 'mys_f_2017', 'mys_f_2018', 'mys_f_2019', 'mys_f_2020', 'mys_f_2021', 'gni_pc_f_1990', 'gni_pc_f_1991', 'gni_pc_f_1992', 'gni_pc_f_1993', 'gni_pc_f_1994', 'gni_pc_f_1995', 'gni_pc_f_1996', 'gni_pc_f_1997', 'gni_pc_f_1998', 'gni_pc_f_1999', 'gni_pc_f_2000', 'gni_pc_f_2001', 'gni_pc_f_2002', 'gni_pc_f_2003', 'gni_pc_f_2004', 'gni_pc_f_2005', 'gni_pc_f_2006', 'gni_pc_f_2007', 'gni_pc_f_2008', 'gni_pc_f_2009', 'gni_pc_f_2010', 'gni_pc_f_2011', 'gni_pc_f_2012', 'gni_pc_f_2013', 'gni_pc_f_2014', 'gni_pc_f_2015', 'gni_pc_f_2016', 'gni_pc_f_2017', 'gni_pc_f_2018', 'gni_pc_f_2019', 'gni_pc_f_2020', 'gni_pc_f_2021', 'hdi_m_1990', 'hdi_m_1991', 'hdi_m_1992', 'hdi_m_1993', 'hdi_m_1994', 'hdi_m_1995', 'hdi_m_1996', 'hdi_m_1997', 'hdi_m_1998', 'hdi_m_1999', 'hdi_m_2000', 'hdi_m_2001', 'hdi_m_2002', 'hdi_m_2003', 'hdi_m_2004', 'hdi_m_2005', 'hdi_m_2006', 'hdi_m_2007', 'hdi_m_2008', 'hdi_m_2009', 'hdi_m_2010', 'hdi_m_2011', 'hdi_m_2012', 'hdi_m_2013', 'hdi_m_2014', 'hdi_m_2015', 'hdi_m_2016', 'hdi_m_2017', 'hdi_m_2018', 'hdi_m_2019', 'hdi_m_2020', 'hdi_m_2021', 'le_m_1990', 'le_m_1991', 'le_m_1992', 'le_m_1993', 'le_m_1994', 'le_m_1995', 'le_m_1996', 'le_m_1997', 'le_m_1998', 'le_m_1999', 'le_m_2000', 'le_m_2001', 'le_m_2002', 'le_m_2003', 'le_m_2004', 'le_m_2005', 'le_m_2006', 'le_m_2007', 'le_m_2008', 'le_m_2009', 'le_m_2010', 'le_m_2011', 'le_m_2012', 'le_m_2013', 'le_m_2014', 'le_m_2015', 'le_m_2016', 'le_m_2017', 'le_m_2018', 'le_m_2019', 'le_m_2020', 'le_m_2021', 'eys_m_1990', 'eys_m_1991', 'eys_m_1992', 'eys_m_1993', 'eys_m_1994', 'eys_m_1995', 'eys_m_1996', 'eys_m_1997', 'eys_m_1998', 'eys_m_1999', 'eys_m_2000', 'eys_m_2001', 'eys_m_2002', 'eys_m_2003', 'eys_m_2004', 'eys_m_2005', 'eys_m_2006', 'eys_m_2007', 'eys_m_2008', 'eys_m_2009', 'eys_m_2010', 'eys_m_2011', 'eys_m_2012', 'eys_m_2013', 'eys_m_2014', 'eys_m_2015', 'eys_m_2016', 'eys_m_2017', 'eys_m_2018', 'eys_m_2019', 'eys_m_2020', 'eys_m_2021', 'mys_m_1990', 'mys_m_1991', 'mys_m_1992', 'mys_m_1993', 'mys_m_1994', 'mys_m_1995', 'mys_m_1996', 'mys_m_1997', 'mys_m_1998', 'mys_m_1999', 'mys_m_2000', 'mys_m_2001', 'mys_m_2002', 'mys_m_2003', 'mys_m_2004', 'mys_m_2005', 'mys_m_2006', 'mys_m_2007', 'mys_m_2008', 'mys_m_2009', 'mys_m_2010', 'mys_m_2011', 'mys_m_2012', 'mys_m_2013', 'mys_m_2014', 'mys_m_2015', 'mys_m_2016', 'mys_m_2017', 'mys_m_2018', 'mys_m_2019', 'mys_m_2020', 'mys_m_2021', 'gni_pc_m_1990', 'gni_pc_m_1991', 'gni_pc_m_1992', 'gni_pc_m_1993', 'gni_pc_m_1994', 'gni_pc_m_1995', 'gni_pc_m_1996', 'gni_pc_m_1997', 'gni_pc_m_1998', 'gni_pc_m_1999', 'gni_pc_m_2000', 'gni_pc_m_2001', 'gni_pc_m_2002', 'gni_pc_m_2003', 'gni_pc_m_2004', 'gni_pc_m_2005', 'gni_pc_m_2006', 'gni_pc_m_2007', 'gni_pc_m_2008', 'gni_pc_m_2009', 'gni_pc_m_2010', 'gni_pc_m_2011', 'gni_pc_m_2012', 'gni_pc_m_2013', 'gni_pc_m_2014', 'gni_pc_m_2015', 'gni_pc_m_2016', 'gni_pc_m_2017', 'gni_pc_m_2018', 'gni_pc_m_2019', 'gni_pc_m_2020', 'gni_pc_m_2021', 'ihdi_2010', 'ihdi_2011', 'ihdi_2012', 'ihdi_2013', 'ihdi_2014', 'ihdi_2015', 'ihdi_2016', 'ihdi_2017', 'ihdi_2018', 'ihdi_2019', 'ihdi_2020', 'ihdi_2021', 'coef_ineq_2010', 'coef_ineq_2011', 'coef_ineq_2012', 'coef_ineq_2013', 'coef_ineq_2014', 'coef_ineq_2015', 'coef_ineq_2016', 'coef_ineq_2017', 'coef_ineq_2018', 'coef_ineq_2019', 'coef_ineq_2020', 'coef_ineq_2021', 'loss_2010', 'loss_2011', 'loss_2012', 'loss_2013', 'loss_2014', 'loss_2015', 'loss_2016', 'loss_2017', 'loss_2018', 'loss_2019', 'loss_2020', 'loss_2021', 'ineq_le_2010', 'ineq_le_2011', 'ineq_le_2012', 'ineq_le_2013', 'ineq_le_2014', 'ineq_le_2015', 'ineq_le_2016', 'ineq_le_2017', 'ineq_le_2018', 'ineq_le_2019', 'ineq_le_2020', 'ineq_le_2021', 'ineq_edu_2010', 'ineq_edu_2011', 'ineq_edu_2012', 'ineq_edu_2013', 'ineq_edu_2014', 'ineq_edu_2015', 'ineq_edu_2016', 'ineq_edu_2017', 'ineq_edu_2018', 'ineq_edu_2019', 'ineq_edu_2020', 'ineq_edu_2021', 'ineq_inc_2010', 'ineq_inc_2011', 'ineq_inc_2012', 'ineq_inc_2013', 'ineq_inc_2014', 'ineq_inc_2015', 'ineq_inc_2016', 'ineq_inc_2017', 'ineq_inc_2018', 'ineq_inc_2019', 'ineq_inc_2020', 'ineq_inc_2021', 'gii_rank_2021', 'gii_1990', 'gii_1991', 'gii_1992', 'gii_1993', 'gii_1994', 'gii_1995', 'gii_1996', 'gii_1997', 'gii_1998', 'gii_1999', 'gii_2000', 'gii_2001', 'gii_2002', 'gii_2003', 'gii_2004', 'gii_2005', 'gii_2006', 'gii_2007', 'gii_2008', 'gii_2009', 'gii_2010', 'gii_2011', 'gii_2012', 'gii_2013', 'gii_2014', 'gii_2015', 'gii_2016', 'gii_2017', 'gii_2018', 'gii_2019', 'gii_2020', 'gii_2021', 'mmr_1990', 'mmr_1991', 'mmr_1992', 'mmr_1993', 'mmr_1994', 'mmr_1995', 'mmr_1996', 'mmr_1997', 'mmr_1998', 'mmr_1999', 'mmr_2000', 'mmr_2001', 'mmr_2002', 'mmr_2003', 'mmr_2004', 'mmr_2005', 'mmr_2006', 'mmr_2007', 'mmr_2008', 'mmr_2009', 'mmr_2010', 'mmr_2011', 'mmr_2012', 'mmr_2013', 'mmr_2014', 'mmr_2015', 'mmr_2016', 'mmr_2017', 'mmr_2018', 'mmr_2019', 'mmr_2020', 'mmr_2021', 'abr_1990', 'abr_1991', 'abr_1992', 'abr_1993', 'abr_1994', 'abr_1995', 'abr_1996', 'abr_1997', 'abr_1998', 'abr_1999', 'abr_2000', 'abr_2001', 'abr_2002', 'abr_2003', 'abr_2004', 'abr_2005', 'abr_2006', 'abr_2007', 'abr_2008', 'abr_2009', 'abr_2010', 'abr_2011', 'abr_2012', 'abr_2013', 'abr_2014', 'abr_2015', 'abr_2016', 'abr_2017', 'abr_2018', 'abr_2019', 'abr_2020', 'abr_2021', 'se_f_1990', 'se_f_1991', 'se_f_1992', 'se_f_1993', 'se_f_1994', 'se_f_1995', 'se_f_1996', 'se_f_1997', 'se_f_1998', 'se_f_1999', 'se_f_2000', 'se_f_2001', 'se_f_2002', 'se_f_2003', 'se_f_2004', 'se_f_2005', 'se_f_2006', 'se_f_2007', 'se_f_2008', 'se_f_2009', 'se_f_2010', 'se_f_2011', 'se_f_2012', 'se_f_2013', 'se_f_2014', 'se_f_2015', 'se_f_2016', 'se_f_2017', 'se_f_2018', 'se_f_2019', 'se_f_2020', 'se_f_2021', 'se_m_1990', 'se_m_1991', 'se_m_1992', 'se_m_1993', 'se_m_1994', 'se_m_1995', 'se_m_1996', 'se_m_1997', 'se_m_1998', 'se_m_1999', 'se_m_2000', 'se_m_2001', 'se_m_2002', 'se_m_2003', 'se_m_2004', 'se_m_2005', 'se_m_2006', 'se_m_2007', 'se_m_2008', 'se_m_2009', 'se_m_2010', 'se_m_2011', 'se_m_2012', 'se_m_2013', 'se_m_2014', 'se_m_2015', 'se_m_2016', 'se_m_2017', 'se_m_2018', 'se_m_2019', 'se_m_2020', 'se_m_2021', 'pr_f_1990', 'pr_f_1991', 'pr_f_1992', 'pr_f_1993', 'pr_f_1994', 'pr_f_1995', 'pr_f_1996', 'pr_f_1997', 'pr_f_1998', 'pr_f_1999', 'pr_f_2000', 'pr_f_2001', 'pr_f_2002', 'pr_f_2003', 'pr_f_2004', 'pr_f_2005', 'pr_f_2006', 'pr_f_2007', 'pr_f_2008', 'pr_f_2009', 'pr_f_2010', 'pr_f_2011', 'pr_f_2012', 'pr_f_2013', 'pr_f_2014', 'pr_f_2015', 'pr_f_2016', 'pr_f_2017', 'pr_f_2018', 'pr_f_2019', 'pr_f_2020', 'pr_f_2021', 'pr_m_1990', 'pr_m_1991', 'pr_m_1992', 'pr_m_1993', 'pr_m_1994', 'pr_m_1995', 'pr_m_1996', 'pr_m_1997', 'pr_m_1998', 'pr_m_1999', 'pr_m_2000', 'pr_m_2001', 'pr_m_2002', 'pr_m_2003', 'pr_m_2004', 'pr_m_2005', 'pr_m_2006', 'pr_m_2007', 'pr_m_2008', 'pr_m_2009', 'pr_m_2010', 'pr_m_2011', 'pr_m_2012', 'pr_m_2013', 'pr_m_2014', 'pr_m_2015', 'pr_m_2016', 'pr_m_2017', 'pr_m_2018', 'pr_m_2019', 'pr_m_2020', 'pr_m_2021', 'lfpr_f_1990', 'lfpr_f_1991', 'lfpr_f_1992', 'lfpr_f_1993', 'lfpr_f_1994', 'lfpr_f_1995', 'lfpr_f_1996', 'lfpr_f_1997', 'lfpr_f_1998', 'lfpr_f_1999', 'lfpr_f_2000', 'lfpr_f_2001', 'lfpr_f_2002', 'lfpr_f_2003', 'lfpr_f_2004', 'lfpr_f_2005', 'lfpr_f_2006', 'lfpr_f_2007', 'lfpr_f_2008', 'lfpr_f_2009', 'lfpr_f_2010', 'lfpr_f_2011', 'lfpr_f_2012', 'lfpr_f_2013', 'lfpr_f_2014', 'lfpr_f_2015', 'lfpr_f_2016', 'lfpr_f_2017', 'lfpr_f_2018', 'lfpr_f_2019', 'lfpr_f_2020', 'lfpr_f_2021', 'lfpr_m_1990', 'lfpr_m_1991', 'lfpr_m_1992', 'lfpr_m_1993', 'lfpr_m_1994', 'lfpr_m_1995', 'lfpr_m_1996', 'lfpr_m_1997', 'lfpr_m_1998', 'lfpr_m_1999', 'lfpr_m_2000', 'lfpr_m_2001', 'lfpr_m_2002', 'lfpr_m_2003', 'lfpr_m_2004', 'lfpr_m_2005', 'lfpr_m_2006', 'lfpr_m_2007', 'lfpr_m_2008', 'lfpr_m_2009', 'lfpr_m_2010', 'lfpr_m_2011', 'lfpr_m_2012', 'lfpr_m_2013', 'lfpr_m_2014', 'lfpr_m_2015', 'lfpr_m_2016', 'lfpr_m_2017', 'lfpr_m_2018', 'lfpr_m_2019', 'lfpr_m_2020', 'lfpr_m_2021', 'rankdiff_hdi_phdi_2021', 'phdi_1990', 'phdi_1991', 'phdi_1992', 'phdi_1993', 'phdi_1994', 'phdi_1995', 'phdi_1996', 'phdi_1997', 'phdi_1998', 'phdi_1999', 'phdi_2000', 'phdi_2001', 'phdi_2002', 'phdi_2003', 'phdi_2004', 'phdi_2005', 'phdi_2006', 'phdi_2007', 'phdi_2008', 'phdi_2009', 'phdi_2010', 'phdi_2011', 'phdi_2012', 'phdi_2013', 'phdi_2014', 'phdi_2015', 'phdi_2016', 'phdi_2017', 'phdi_2018', 'phdi_2019', 'phdi_2020', 'phdi_2021', 'diff_hdi_phdi_1990', 'diff_hdi_phdi_1991', 'diff_hdi_phdi_1992', 'diff_hdi_phdi_1993', 'diff_hdi_phdi_1994', 'diff_hdi_phdi_1995', 'diff_hdi_phdi_1996', 'diff_hdi_phdi_1997', 'diff_hdi_phdi_1998', 'diff_hdi_phdi_1999', 'diff_hdi_phdi_2000', 'diff_hdi_phdi_2001', 'diff_hdi_phdi_2002', 'diff_hdi_phdi_2003', 'diff_hdi_phdi_2004', 'diff_hdi_phdi_2005', 'diff_hdi_phdi_2006', 'diff_hdi_phdi_2007', 'diff_hdi_phdi_2008', 'diff_hdi_phdi_2009', 'diff_hdi_phdi_2010', 'diff_hdi_phdi_2011', 'diff_hdi_phdi_2012', 'diff_hdi_phdi_2013', 'diff_hdi_phdi_2014', 'diff_hdi_phdi_2015', 'diff_hdi_phdi_2016', 'diff_hdi_phdi_2017', 'diff_hdi_phdi_2018', 'diff_hdi_phdi_2019', 'diff_hdi_phdi_2020', 'diff_hdi_phdi_2021', 'co2_prod_1990', 'co2_prod_1991', 'co2_prod_1992', 'co2_prod_1993', 'co2_prod_1994', 'co2_prod_1995', 'co2_prod_1996', 'co2_prod_1997', 'co2_prod_1998', 'co2_prod_1999', 'co2_prod_2000', 'co2_prod_2001', 'co2_prod_2002', 'co2_prod_2003', 'co2_prod_2004', 'co2_prod_2005', 'co2_prod_2006', 'co2_prod_2007', 'co2_prod_2008', 'co2_prod_2009', 'co2_prod_2010', 'co2_prod_2011', 'co2_prod_2012', 'co2_prod_2013', 'co2_prod_2014', 'co2_prod_2015', 'co2_prod_2016', 'co2_prod_2017', 'co2_prod_2018', 'co2_prod_2019', 'co2_prod_2020', 'co2_prod_2021', 'mf_1990', 'mf_1991', 'mf_1992', 'mf_1993', 'mf_1994', 'mf_1995', 'mf_1996', 'mf_1997', 'mf_1998', 'mf_1999', 'mf_2000', 'mf_2001', 'mf_2002', 'mf_2003', 'mf_2004', 'mf_2005', 'mf_2006', 'mf_2007', 'mf_2008', 'mf_2009', 'mf_2010', 'mf_2011', 'mf_2012', 'mf_2013', 'mf_2014', 'mf_2015', 'mf_2016', 'mf_2017', 'mf_2018', 'mf_2019', 'mf_2020', 'mf_2021']

QUESTION-2

In [ ]:
hdi_column = df['hdi_2020']
print(hdi_column.head())

0    0.483
1    0.590
2    0.794
3    0.848
4    0.912
Name: hdi_2020, dtype: float64

In [ ]:
hdi_column = df['hdi_2021']
print(hdi_column.head())

0    0.478
1    0.586
2    0.796
3    0.858
4    0.911
Name: hdi_2021, dtype: float64

In [ ]:
print(f"Average HDI Value: {df['hdi_rank_2021'].mean():.3f}")
print(f"Highest HDI Value: {df['hdi_rank_2021'].max():.3f}")

Average HDI Value: 95.812
Highest HDI Value: 191.000

In [ ]:
high_hdi_countries = df[df['hdi_rank_2021'] > 0.8][['country', 'hdi_rank_2021']]
print(high_hdi_countries.head())

                country  hdi_rank_2021
0           Afghanistan          180.0
1                Angola          148.0
2               Albania           67.0
3               Andorra           40.0
4  United Arab Emirates           26.0

In [ ]:
df['hdi_growth'] = df['hdi_rank_2021'] - df['hdi_2000']
print(df[['country', 'hdi_growth']].head())

                country  hdi_growth
0           Afghanistan     179.665
1                Angola     147.625
2               Albania      66.323
3               Andorra      39.182
4  United Arab Emirates      25.204

  QUESTION-3

In [ ]:
numerical_cols = ['le_2021', 'hdi_2021', 'mys_2021', 'eys_2021', 'gnipc_2021']
corr_matrix = df[numerical_cols].corr()
print(corr_matrix)

             le_2021  hdi_2021  mys_2021  eys_2021  gnipc_2021
le_2021     1.000000  0.907492  0.737159  0.781270    0.734441
hdi_2021    0.907492  1.000000  0.909831  0.897828    0.789149
mys_2021    0.737159  0.909831  1.000000  0.782997    0.656626
eys_2021    0.781270  0.897828  0.782997  1.000000    0.642778
gnipc_2021  0.734441  0.789149  0.656626  0.642778    1.000000

In [ ]:
print(corr_matrix['le_2021'].sort_values(ascending=False))

le_2021       1.000000
hdi_2021      0.907492
eys_2021      0.781270
mys_2021      0.737159
gnipc_2021    0.734441
Name: le_2021, dtype: float64

QSN-4

In [ ]:
df['gni_growth_pct'] = ((df['gnipc_2021'] - df['gnipc_2000']) / df['gnipc_2000']) * 100

In [ ]:
top_gni_wealth = df.nlargest(10, 'gni_growth_pct')[['country', 'gni_growth_pct']]

In [ ]:
print(top_gni_wealth)

                              country  gni_growth_pct
71                             Guyana      441.134178
32                              China      412.351653
117                           Myanmar      299.435127
200         East Asia and the Pacific      279.629337
10                         Azerbaijan      260.874836
55                           Ethiopia      225.406617
6                             Armenia      214.905941
104                         Lithuania      195.971385
185                        Uzbekistan      188.824141
96   Lao People's Democratic Republic      183.587832

In [ ]:
print(df['gni_growth_pct'])

0       85.197530
1       48.095448
2      132.986900
3        6.932433
4      -40.201239
          ...
201    114.031145
202     21.042633
203    122.029642
204     41.243054
205     52.175801
Name: gni_growth_pct, Length: 206, dtype: float64

In [ ]:
print(top_gni_wealth.to_string(index=False))

                         country  gni_growth_pct
                          Guyana      441.134178
                           China      412.351653
                         Myanmar      299.435127
       East Asia and the Pacific      279.629337
                      Azerbaijan      260.874836
                        Ethiopia      225.406617
                         Armenia      214.905941
                       Lithuania      195.971385
                      Uzbekistan      188.824141
Lao People's Democratic Republic      183.587832

In [40]:
import pandas as pd
import sqlite3

df=pd.read_csv('/content/HDI.csv')

In [41]:
conn=sqlite3.connect('hdi.db')

In [42]:
df.to_sql('hdi_table',conn,if_exists='replace',index=False)

206

In [43]:
conn.close()

In [44]:
import pandas as pd
import sqlite3
conn=sqlite3.connect('hdi.db')

In [45]:
df_check=pd.read_sql_query('SELECT * FROM hdi_table LIMIT 5',conn)

In [46]:
df_check

,iso3,country,hdicode,region,hdi_rank_2021,hdi_1990,hdi_1991,hdi_1992,hdi_1993,hdi_1994,...,mf_2012,mf_2013,mf_2014,mf_2015,mf_2016,mf_2017,mf_2018,mf_2019,mf_2020,mf_2021
0,AFG,Afghanistan,Low,SA,180.0,0.273,0.279,0.287,0.297,0.292,...,1.86,1.88,1.66,1.62,1.66,1.41,1.32,1.38,1.38,1.38
1,AGO,Angola,Medium,SSA,148.0,NaN,NaN,NaN,NaN,NaN,...,4.09,4.53,3.97,3.59,2.79,2.64,2.28,2.18,2.18,2.18
2,ALB,Albania,High,ECA,67.0,0.647,0.629,0.614,0.617,0.624,...,12.44,11.49,13.14,12.61,14.39,14.46,12.85,12.96,12.96,12.96
3,AND,Andorra,Very High,None,40.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ARE,United Arab Emirates,Very High,AS,26.0,0.728,0.739,0.742,0.748,0.755,...,49.56,49.68,55.49,59.76,64.95,75.61,65.97,68.95,68.95,68.95

In [49]:

query="""
SELECT country, hdi_rank_2021
FROM hdi_table
WHERE hdi_rank_2021 > 0.8
ORDER BY hdi_rank_2021 DESC;
"""
df_high_hdi=pd.read_sql_query(query,conn)
df_high_hdi

                      country  hdi_rank_2021
0                 South Sudan          191.0
1                        Chad          190.0
2                       Niger          189.0
3    Central African Republic          188.0
4                     Burundi          187.0
..                        ...            ...
186                 Australia            5.0
187    Hong Kong, China (SAR)            4.0
188                   Iceland            3.0
189                    Norway            2.0
190               Switzerland            1.0

[191 rows x 2 columns]

In [54]:
query_q2="""
SELECT Region,
       MIN(hdi_rank_2021) AS min_hdi_rank,
       MAX(hdi_rank_2021) AS max_hdi_rank,
       (MAX(hdi_rank_2021)-MIN(hdi_rank_2021)) AS HDI_GROWTH
FROM hdi_table
-- WHERE Year>=2000
GROUP BY Region
ORDER BY HDI_GROWTH DESC;
"""
df_hdi_stats=pd.read_sql_query(query_q2,conn)
df_hdi_stats

  region  min_hdi_rank  max_hdi_rank  HDI_GROWTH
0     AS          26.0         183.0       157.0
1    EAP          12.0         156.0       144.0
2    SSA          63.0         191.0       128.0
3    LAC          42.0         163.0       121.0
4     SA          73.0         180.0       107.0
5    ECA          48.0         122.0        74.0
6   None           1.0          68.0        67.0

QUESTION 3

In [58]:
QUERY_Q3="""
WITH StatComponents AS (
    SELECT
        COUNT(*) AS N,
        SUM(le_2021) AS Sum_X,
        SUM(gnipc_2021) AS Sum_Y,
        SUM(le_2021 * le_2021) AS Sum_X2,
        SUM(gnipc_2021 * gnipc_2021) AS Sum_Y2,
        SUM(le_2021 * gnipc_2021) AS Sum_XY
    FROM hdi_table
    WHERE le_2021 IS NOT NULL
      AND gnipc_2021 IS NOT NULL
)


SELECT
    --Covariance numerator: (N * ΣXY) - (ΣX * ΣY)
    ((N * Sum_XY) - (Sum_X * Sum_Y))
    /
    --Standard deviation denominator: √[N*ΣX² - (ΣX)²] * √[N*ΣY² - (ΣY)²]
    (
        SQRT((N * Sum_X2) - (Sum_X * Sum_X))
        *
        SQRT((N * Sum_Y2) - (Sum_Y * Sum_Y))
    ) AS pearson_correlation_r
FROM StatComponents;
"""
df_hdi_stats_query3=pd.read_sql_query(QUERY_Q3,conn)
df_hdi_stats_query3

   pearson_correlation_r
0               0.734441

QUESTION 4

In [60]:
query_4 = """
SELECT
    -- 1. General Metrics
    COUNT(CASE WHEN hdicode = 'High' THEN 1 END) AS high_inc_count, -- Changed 'High Income' to 'High'
    COUNT(CASE WHEN hdicode = 'Low' THEN 1 END) AS low_inc_count, -- Changed 'Low Income' to 'Low'

    -- 2. Life Expectancy Comparisons & Gap
    ROUND(AVG(CASE WHEN hdicode = 'High' THEN le_2021 END), 1) AS high_inc_avg_life_exp, -- Changed 'High Income' to 'High', 'life_expectancy' to 'le_2021'
    ROUND(AVG(CASE WHEN hdicode = 'Low' THEN le_2021 END), 1) AS low_inc_avg_life_exp, -- Changed 'Low Income' to 'Low', 'life_expectancy' to 'le_2021'
    ROUND(
        AVG(CASE WHEN hdicode = 'High' THEN le_2021 END) -  -- Changed 'High Income' to 'High', 'life_expectancy' to 'le_2021'
        AVG(CASE WHEN hdicode = 'Low' THEN le_2021 END), 1 -- Changed 'Low Income' to 'Low', 'life_expectancy' to 'le_2021'
    ) AS life_exp_gap_years,

    -- 3. Education Comparisons & Gap
    ROUND(AVG(CASE WHEN hdicode = 'High' THEN mys_2021 END), 1) AS high_inc_avg_schooling, -- Changed 'High Income' to 'High', 'mean_years_schooling' to 'mys_2021'
    ROUND(AVG(CASE WHEN hdicode = 'Low' THEN mys_2021 END), 1) AS low_inc_avg_schooling, -- Changed 'Low Income' to 'Low', 'mean_years_schooling' to 'mys_2021'
    ROUND(
        AVG(CASE WHEN hdicode = 'High' THEN mys_2021 END) -  -- Changed 'High Income' to 'High', 'mean_years_schooling' to 'mys_2021'
        AVG(CASE WHEN hdicode = 'Low' THEN mys_2021 END), 1 -- Changed 'Low Income' to 'Low', 'mean_years_schooling' to 'mys_2021'
    ) AS schooling_gap_years,

    -- 4. Economic (GNI) Comparisons & Multiplier
    ROUND(AVG(CASE WHEN hdicode = 'High' THEN gnipc_2021 END), 0) AS high_inc_avg_gni, -- Changed 'High Income' to 'High', 'gni_per_capita' to 'gnipc_2021'
    ROUND(AVG(CASE WHEN hdicode = 'Low' THEN gnipc_2021 END), 0) AS low_inc_avg_gni, -- Changed 'Low Income' to 'Low', 'gni_per_capita' to 'gnipc_2021'
    ROUND(
        AVG(CASE WHEN hdicode = 'High' THEN gnipc_2021 END) /  -- Changed 'High Income' to 'High', 'gni_per_capita' to 'gnipc_2021'
        NULLIF(AVG(CASE WHEN hdicode = 'Low' THEN gnipc_2021 END), 0), 1 -- Changed 'Low Income' to 'Low', 'gni_per_capita' to 'gnipc_2021'
    ) AS gni_multiplier_fold

FROM hdi_table -- Changed 'country_metrics' to 'hdi_table'
WHERE hdicode IN ('High', 'Low'); -- Changed 'income_group' to 'hdicode' and 'High Income'/'Low Income' to 'High'/'Low'
"""
df_hdi_stats_query_4=pd.read_sql_query(query_4,conn)
df_hdi_stats_query_4

,high_inc_count,low_inc_count,high_inc_avg_life_exp,low_inc_avg_life_exp,life_exp_gap_years,high_inc_avg_schooling,low_inc_avg_schooling,schooling_gap_years,high_inc_avg_gni,low_inc_avg_gni,gni_multiplier_fold
0,49,32,72.1,61.0,11.0,9.8,4.3,5.5,13232.0,2212.0,6.0

In [61]:
import pandas as pd


csv_path = "hdi.csv"
df = pd.read_csv("/content/HDI.csv")

parquet_path = "hdi.parquet"
df.to_parquet(parquet_path, engine="pyarrow", compression="snappy", index=False)

print(f" Converted '{csv_path}' to optimized Parquet at '{parquet_path}'")

 Converted 'hdi.csv' to optimized Parquet at 'hdi.parquet'

In [62]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, count, round

In [63]:
spark = SparkSession.builder \
    .appName("HDIDataParquetAnalysis") \
    .config("spark.sql.parquet.compression.codec", "snappy") \
    .getOrCreate()

In [65]:
csv_path = "hdi.csv"
df = spark.read.csv("/content/HDI.csv", header=True, inferSchema=True)

In [66]:
parquet_output_path = "hdi.parquet"
df.write.mode("overwrite").parquet(parquet_output_path)
parquet_output_path = "hdi.parquet"
df.write.mode("overwrite").parquet(parquet_output_path)
print(f"Success: Converted '{csv_path}' to optimized Parquet format at '{parquet_output_path}'")

Success: Converted 'hdi.csv' to optimized Parquet format at 'hdi.parquet'

In [67]:
parquet_df = spark.read.parquet(parquet_output_path)

In [70]:
differentiation_analysis = parquet_df \
    .filter(col("hdicode").isin("High", "Low")) \
    .groupBy("hdicode") \
    .agg(
        count("country").alias("country_count"),
        round(avg("le_2021"), 1).alias("avg_life_expectancy"),
        round(avg("mys_2021"), 1).alias("avg_years_schooling"),
        round(avg("gnipc_2021"), 0).alias("avg_gni_per_capita")
    )

In [71]:
print(differentiation_analysis.show())

+-------+-------------+-------------------+-------------------+------------------+
|hdicode|country_count|avg_life_expectancy|avg_years_schooling|avg_gni_per_capita|
+-------+-------------+-------------------+-------------------+------------------+
|   High|           49|               72.1|                9.8|           13232.0|
|    Low|           32|               61.0|                4.3|            2212.0|
+-------+-------------+-------------------+-------------------+------------------+

None

In [75]:

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, round
from pyspark.sql.window import Window
from pyspark.sql.functions import desc

spark = SparkSession.builder \
    .appName("HDIGrowthOverlapAnalysis") \
    .getOrCreate()

df = spark.read.parquet("hdi.parquet")

growth_df = df.withColumn(
    "gni_growth_pct",
    round(((col("gnipc_2021") - col("gnipc_1990")) / col("gnipc_1990")) * 100, 2)
)



top_gni = growth_df.select("country", "gni_growth_pct") \
    .orderBy(desc("gni_growth_pct")) \
    .limit(20)



print("TOP 10 GNI GROWTH COUNTRIES")
top_gni.show(10, truncate=False)

TOP 10 GNI GROWTH COUNTRIES
+--------------------------------+--------------+
|country                         |gni_growth_pct|
+--------------------------------+--------------+
|China                           |1091.99       |
|Guyana                          |996.29        |
|Myanmar                         |618.5         |
|East Asia and the Pacific       |597.79        |
|Viet Nam                        |398.07        |
|Cambodia                        |304.79        |
|Lao People's Democratic Republic|296.07        |
|India                           |268.07        |
|Bangladesh                      |252.04        |
|Korea (Republic of)             |252.03        |
+--------------------------------+--------------+
only showing top 10 rows

In [78]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, round, desc

spark = SparkSession.builder.appName("RegionalHDIGrowth").getOrCreate()


df = spark.read.parquet("hdi.parquet")

regional_growth = df.groupBy("region") \
    .agg(
        round(avg("hdi_2000"), 3).alias("avg_hdi_2000"),
        round(avg("hdi_2021"), 3).alias("avg_hdi_latest"),
        round(
            (avg("hdi_2021") - avg("hdi_2000")), 3
        ).alias("absolute_hdi_growth"),
        round(
            ((avg("hdi_2021") - avg("hdi_2000")) / avg("hdi_2000")) * 100, 1
        ).alias("percentage_growth_pct")
    ) \
    .orderBy(desc("absolute_hdi_growth"))

regional_growth.show(truncate=False)

+------+------------+--------------+-------------------+---------------------+
|region|avg_hdi_2000|avg_hdi_latest|absolute_hdi_growth|percentage_growth_pct|
+------+------------+--------------+-------------------+---------------------+
|SA    |0.528       |0.654         |0.127              |24.0                 |
|ECA   |0.659       |0.772         |0.113              |17.2                 |
|SSA   |0.437       |0.543         |0.107              |24.4                 |
|EAP   |0.607       |0.691         |0.084              |13.8                 |
|NULL  |0.783       |0.864         |0.081              |10.3                 |
|AS    |0.64        |0.718         |0.078              |12.2                 |
|LAC   |0.67        |0.74          |0.07               |10.5                 |
+------+------------+--------------+-------------------+---------------------+

QUESTION 3

In [83]:

from pyspark.sql import SparkSession
from pyspark.sql.functions import col


spark = SparkSession.builder \
    .appName("LifeExpectancyCorrelation") \
    .getOrCreate()

df = spark.read.parquet("hdi.parquet")


target_column = "le_2021"
factors = [
    "hdi_2021",
    "mys_2021",
    "eys_2021",
    "gnipc_2021"
]

print(f"Correlation Matrix for {target_column}")
for factor in factors:
    correlation = df.corr(target_column, factor)
    print(f"Correlation between {target_column} and {factor}: {correlation}")

Correlation Matrix for le_2021
Correlation between le_2021 and hdi_2021: 0.7522201621641518
Correlation between le_2021 and mys_2021: 0.6807410839081771
Correlation between le_2021 and eys_2021: 0.698391996479701
Correlation between le_2021 and gnipc_2021: 0.7145878938199742

QUESTION 4

In [86]:

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, avg, count, round


spark = SparkSession.builder \
    .appName("IncomeGroupDifferentiation") \
    .getOrCreate()
df = spark.read.parquet("hdi.parquet")

analysis_df = df \
    .filter(col("hdicode").isin("High", "Low")) \
    .groupBy("hdicode") \
    .agg(
        count("country").alias("total_countries"),
        round(avg("le_2021"), 1).alias("avg_life_exp"),
        round(avg("mys_2021"), 1).alias("avg_schooling_years"),
        round(avg("eys_2021"), 1).alias("avg_expected_schooling"),
        round(avg("gnipc_2021"), 0).alias("avg_gni_per_capita"),
        round(avg("hdi_2021"), 3).alias("avg_hdi")
    )


print("DECISIVE STRUCTURAL VARIANCES (HIGH VS LOW INCOME)")
analysis_df.show(truncate=False)


# spark.stop() # Removed spark.stop() to keep the session alive

DECISIVE STRUCTURAL VARIANCES (HIGH VS LOW INCOME)
+-------+---------------+------------+-------------------+----------------------+------------------+-------+
|hdicode|total_countries|avg_life_exp|avg_schooling_years|avg_expected_schooling|avg_gni_per_capita|avg_hdi|
+-------+---------------+------------+-------------------+----------------------+------------------+-------+
|High   |49             |72.1        |9.8                |14.0                  |13232.0           |0.747  |
|Low    |32             |61.0        |4.3                |9.5                   |2212.0            |0.484  |
+-------+---------------+------------+-------------------+----------------------+------------------+-------+

In [87]:
!pip install trino pandas

Collecting trino
  Downloading trino-0.339.0-py3-none-any.whl.metadata (21 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Collecting lz4 (from trino)
  Downloading lz4-4.4.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (3.8 kB)
Requirement already satisfied: orjson>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from trino) (3.12.0)
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.13/dist-packages (from trino) (2.9.0.post0)
Requirement already satisfied: pytz in /usr/local/lib/python3.13/dist-packages (from trino) (2025.2)
Requirement already satisfied: requests>=2.32.4 in /usr/local/lib/python3.13/dist-packages (from trino) (2.32.4)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.13/dist-packages (from trino) (5.4.4)
Requirement already satisfied: zstandard in /usr/local/lib/python3.13/dist-packages (from trino) (0.25.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil->trino) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.4->trino) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.4->trino) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.4->trino) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests>=2.32.4->trino) (2026.7.22)
Downloading trino-0.339.0-py3-none-any.whl (62 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.9/62.9 kB 3.7 MB/s eta 0:00:00
Downloading lz4-4.4.5-cp313-cp313-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 MB 33.4 MB/s eta 0:00:00
Installing collected packages: lz4, trino
Successfully installed lz4-4.4.5 trino-0.339.0

In [91]:
import pandas as pd
from trino.dbapi import connect
from trino.auth import BasicAuthentication

def get_trino_connection():

    return connect(
        host="localhost",
        port=8080,
        user="trino_user",
        catalog="hive",
        schema="default",

    )